name: Kent Liau
author: Kent Liau
url: http://blog.kent.li
description: "About Workflow"
meta_description:

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis",
               "fenced_code_blocks",
               "autolink",
               "tables",
               "with_toc_data",
               "strikethrough"]
highlighter: pygments

#excerpt_separator: <!-- more -->

# Permalinks
permalink: /:categories/:title/

# Server
#source:           src
#destination:      _gh_pages
#host:             0.0.0.0
#url:              localhost
#port:             9001
#baseurl:          /
#encoding:         UTF-8

logo: false
paginate_path: '/page/:num'
paginate:      5

exclude: ["README.md"]

include: [".htaccess"]
